name: Master
on:
  push:
    branches: [master]
concurrency:
  group: master
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Write version.json
        run: echo ${{github.run_number}} > version.json

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: pickrelated
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build dev docker image and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./Dockerfile
          push: true
          tags: pickrelated/websocket-broadcast-relay:latest
